name: C Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GCC
      run: sudo apt-get install -y gcc

    - name: Build tests
      run: gcc test_math.c ../src/math.c -o test_math

    - name: Run tests
      run: ./test_math